services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    container_name: keycloak
    network_mode: host
    command: 
      - start-dev
      - --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8080
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /realms/master HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  trino:
    image: trinodb/trino:470
    container_name: trino
    network_mode: host
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/docker-entrypoint.sh:/docker-entrypoint.sh
    env_file:
      - .env
    entrypoint: ["/bin/bash", "/docker-entrypoint.sh"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f -k https://localhost:8443/v1/info || curl -f http://localhost:8080/v1/info || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
    depends_on:
      keycloak:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    network_mode: host
    environment:
      - NODE_ENV=development
      - PORT=3001
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    env_file:
      - .env
    depends_on:
      trino:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

