services:
  trino:
    image: trinodb/trino:470
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/docker-entrypoint.sh:/docker-entrypoint.sh
    env_file:
      - .env
    entrypoint: ["/bin/bash", "/docker-entrypoint.sh"]
    networks:
      - trino-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/v1/info || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - .env
    networks:
      - trino-network
    depends_on:
      trino:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - trino-network
    depends_on:
      - backend

networks:
  trino-network:
    driver: bridge
